### ISSUE TITLE
REQ_A Linux .clap version of this beauty, it is possible?

### ISSUE THREAD

**Issue by ghost** [Mrugalla/Manta#5]
Linux Mint 21.3_x64_Cinnamom
Hi,

hello,
I'm one of the many LINUX users and I'm trying to "push" for the .clap format in the versions of the various plugins (especially free and open source projects, like this). Is it possible to have this beautiful project (or all your plugins) in this format TOO?

thanks again

**Comment by Mrugalla** [comment]
The problem is trivial: I haven't properly learned cmake yet and the projucer doesn't support CLAP yet. One of these things has to change, then there will be CLAP builds. Another option would be that someone, who knows how to build JUCE plugins for CLAP just compiles them for me, but didn't happen so far

**Comment by ghost** [comment]
Oh, thank you so much for your response. I hope that one day, maybe even just in VST, you can also open up the Linux world
However, I would like to thank you for your work. I found this wonderful tool of yours presented in this video:

https://www.youtube.com/watch?v=-YfoNKVMxlg

Cheers
